### ISSUE TITLE
Random values

### ISSUE THREAD

**Issue by smartVanture** [ard00d/renogy-bt2-ha-ble#1]
Hi, 
first of all thanks a lot for providing this project! I'm trying to make my new self converted van as smart as possible but since I'm not a big of a coder, I couldn't get my Renogy System (2 175W solar panels, one MPPT booster, 2 100Ah LiFePo4 batteries and one 2000W inverter) integrated into my Home Assistant. But your code and instructions actually did it! 
However, for now it seems that I get pretty random values which also fluctuate pretty much. In rare moments they seem to be valid but most of the time they are far off. For example I get battery temperatures of -77°C, battery Voltages of over 3000V or accumulated amp hours of over a billion. Do you have any idea what the problem could be? 
Apperciate your support!
Thanks
Jens

**Comment by ard00d** [comment]
Are you trying to read values from a DCC50S, or a different Renogy device? I only tested against the DCC50S, so any other device might need code changes. Without having the same device for testing against, it would be difficult to provide any suggestions.

Also, I have sold my Renogy gear and am no longer using this. Overall, I have found bluetooth monitoring to be flaky with several different devices (Victron seems to work okay). I've gotten more reliable monitoring using directly connected ESP32 modules (modbus).

The signal between my Pi4 and the BT-2 module was always kind of weak. You might want to check the quality of your Bluetooth signal and move them closer together if it seems like it works some of the time, but not all.

**Comment by smartVanture** [comment]
Thanks for your quick response!
 
That's right, I'm trying to pull from a DCC50S which is connected to my BT-2 module through the communication hub as well as my two LiFiPo4 Batteries. Should I try and disconnect the batteries from the hub? But there are also entities for the batteries so I thought they might also push data. 

And yes, bluetooth connection is a huge pain especially with the app. I was hoping, that it would be better through your script and home assistant. But directly pulling into an ESP32 sounds good as I have several in use. I just don't have any experience with thtat. So that would be from the RJ45 port to the GPIOs?

**Comment by ard00d** [comment]
I'm guessing the code would need an update to filter the responses from the batteries. They are probably using the same registers, but representing different values
