### ISSUE TITLE
Not able to connect simultaneously to Renogy Core One and Rpi

### ISSUE THREAD

**Issue by didi767** [ard00d/renogy-bt2-ha-ble#2]
Hi,

Is this something related to the integration or a general limitation that the BT-2 can't connect with 2 clients?

Regards,
Didi

**Comment by smartVanture** [comment]
Yeah same here. If it's connected to my Pi, I can't connect through the app. That might be the reason why the script disconnects at the end and he recommends a cronjob with a 5min interval instead of a continuous service?

**Comment by didi767** [comment]
It would be able to connect then?
I think once it's connected to the app, we have to disconnect it manually and then let the pi run. Tlat least from what I've noticed.
At first I thought that the script is just sniffing the traffic between the app and the components so it should not be an issue

**Comment by ard00d** [comment]
The BT-2 only supported one connection at a time. If continuously connected to the Pi, the phone app won't work, and vice-versa.
