### ISSUE TITLE
https://github.com/durib/ha-renogy-bt2-ble is not a valid add-on repository

### ISSUE THREAD

**Issue by haitonno** [ard00d/renogy-bt2-ha-ble#3]
running HOAS on Raspi Pi 4B
with
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

Trying to add this Repository from Store with https://github.com/durib/ha-renogy-bt2-ble is not a valid add-on repository

HOAS says: https://github.com/durib/ha-renogy-bt2-ble is not a valid add-on repository

I'm happy I found this add-on, would be happier, if it works :-)

**Comment by smartVanture** [comment]
It's not an add on 😉 
The install section describes how to integrate it.

**Comment by ard00d** [comment]
Correct, this is not integrated with the HA store. There will be no further development on this project unless someone else takes it over.

**Comment by haitonno** [comment]
what am i wrong? ard00d is not an itegration, but durib fork seems to be one. Please help, because i am an obolsute newbea on that
